Disable tests that use the old logic.
While the test should be passing anyway, as they are unused with
read-only flag enabled, some parts of the class are not compiled,
and tests fail with `NoSuchMethodError`.

Flag: EXEMPT test-only change
Fixes: 415775558
Test: atest SettingsUnitTests:UserAspectRatioRestoreStorageTest
Change-Id: I4dd245a0518b6f9ba7da853a6fe3c96dc4879b12